[project]
name = "simple-rnn-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ipykernel>=7.3.0",
    "keras>=3.15.1",
    "numpy>=2.4.6",
    "pandas>=3.0.5",
    "streamlit>=1.63.0",
    "tensorflow>=2.21.0",
]
